<Project>
  <PropertyGroup>
    <Version>0.12.7</Version>
    <Copyright>sa_ddam213 - 2026</Copyright>
    <RepositoryUrl>https://github.com/saddam213/TensorStack</RepositoryUrl>
    <PackageTags>onnx;onnx-runtime;</PackageTags>
    <Authors>sa_ddam213</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PackageOutputPath>..\..\Nuget</PackageOutputPath>
    <Configurations>Debug;Release;</Configurations>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <TargetFrameworks>net10.0-windows10.0.17763.0</TargetFrameworks>
  </PropertyGroup>
</Project>