<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <!--Projects-->
  <ItemGroup Condition=" '$(Configuration)' == 'Debug'">
    <ProjectReference Include="..\TensorStack.Common\TensorStack.Common.csproj" />
  </ItemGroup>

  <!--Packages-->
  <ItemGroup Condition=" '$(Configuration)' == 'Release'">
    <PackageReference Include="TensorStack.Common" Version="$(Version)" />
  </ItemGroup>

    <!--Common Packages-->
  <ItemGroup>
    <PackageReference Include="OpenCvSharp5" Version="5.0.0.20260905" />
    <PackageReference Include="OpenCvSharp5.runtime.win" Version="5.0.0.20260905" />
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
    <PackageReference Include="SkiaSharp" Version="4.151.2" />
  </ItemGroup>

  <!--Binaries-->
  <ItemGroup>
    <Content Include="ffmpeg.exe" Pack="true" PackagePath="contentFiles\any\any\" CopyToOutputDirectory="Always" PackageCopyToOutput="true" />
    <None Include="ffmpeg.exe" Pack="false" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ffprobe.exe" Pack="true" PackagePath="contentFiles\any\any\" CopyToOutputDirectory="Always" PackageCopyToOutput="true" />
    <None Include="ffprobe.exe" Pack="false" />
  </ItemGroup>

  <!--Nuget Settings-->
  <PropertyGroup>
    <Title>$(AssemblyName)</Title>
    <PackageId>$(AssemblyName)</PackageId>
    <Product>$(AssemblyName)</Product>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Image/Audio/Video tensor operations for .NET using ONNX Runtime</Description>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <None Remove="README.md" />
    <None Remove="Icon.png" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\Assets\Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>