<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <!--Projects-->
  <ItemGroup Condition=" '$(Configuration)' == 'Debug'">
    <ProjectReference Include="..\TensorStack.Common\TensorStack.Common.csproj" />
    <ProjectReference Include="..\TensorStack.Media\TensorStack.Media.csproj" />
  </ItemGroup>

  <!--Packages-->
  <ItemGroup Condition=" '$(Configuration)' == 'Release'">
    <PackageReference Include="TensorStack.Common" Version="$(Version)" />
    <PackageReference Include="TensorStack.Media" Version="$(Version)" />
  </ItemGroup>

  <!--Common Packages-->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.158" />
  </ItemGroup>

  <!--Images-->
  <ItemGroup>
    <Resource Include="Images\Icon.ico" />
    <Resource Include="Images\Icon.png" />
    <Resource Include="Images\Icon-Large.png" />
    <Resource Include="Images\PlaceholderAudio.png" />
    <Resource Include="Images\PlaceholderImage.png" />
    <Resource Include="Images\PlaceholderText.png" />
    <Resource Include="Images\PlaceholderVideo.png" />
    <Resource Include="Images\Tensorstack-720-Gray.png" />
    <Resource Include="Images\Tensorstack-720.png" />
    <Resource Include="Images\tensorstack-long.png" />
    <Resource Include="Images\Tensorstack-Text.png" />
    <Resource Include="Images\Tensorstack.png" />
  </ItemGroup>

  <!--Binaries-->
  <ItemGroup>
    <Reference Include="ColorPicker">
      <HintPath>ColorPicker.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="ColorPicker.dll" PackagePath="lib/net10.0-windows10.0.17763/">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Pack>true</Pack>
    </None>
  </ItemGroup>

  <!--Nuget Settings-->
  <PropertyGroup>
    <Title>$(AssemblyName)</Title>
    <PackageId>$(AssemblyName)</PackageId>
    <Product>$(AssemblyName)</Product>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <None Remove="README.md" />
    <None Remove="Icon.png" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\Assets\Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\Default.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Default.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Enums.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Enums.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Errors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ToolTips.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ToolTips.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Default.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Default.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Enums.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Enums.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Errors.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ToolTips.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ToolTips.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
