//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TensorStack.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TensorStack.WPF.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DragDropType0 {
            get {
                return ResourceManager.GetString("DragDropType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string DragDropType1 {
            get {
                return ResourceManager.GetString("DragDropType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string DragDropType2 {
            get {
                return ResourceManager.GetString("DragDropType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string DragDropType3 {
            get {
                return ResourceManager.GetString("DragDropType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string DragDropType4 {
            get {
                return ResourceManager.GetString("DragDropType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation.
        /// </summary>
        public static string DragDropType5 {
            get {
                return ResourceManager.GetString("DragDropType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ImageEditMode0 {
            get {
                return ResourceManager.GetString("ImageEditMode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string ImageEditMode1 {
            get {
                return ResourceManager.GetString("ImageEditMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        public static string ImageEditMode2 {
            get {
                return ResourceManager.GetString("ImageEditMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string ImageEditMode3 {
            get {
                return ResourceManager.GetString("ImageEditMode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ImageEditMode4 {
            get {
                return ResourceManager.GetString("ImageEditMode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MessageBoxIconType0 {
            get {
                return ResourceManager.GetString("MessageBoxIconType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxIconType1 {
            get {
                return ResourceManager.GetString("MessageBoxIconType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageBoxIconType2 {
            get {
                return ResourceManager.GetString("MessageBoxIconType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxIconType3 {
            get {
                return ResourceManager.GetString("MessageBoxIconType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxIconType4 {
            get {
                return ResourceManager.GetString("MessageBoxIconType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MessageBoxStyleType0 {
            get {
                return ResourceManager.GetString("MessageBoxStyleType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageBoxStyleType1 {
            get {
                return ResourceManager.GetString("MessageBoxStyleType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxStyleType2 {
            get {
                return ResourceManager.GetString("MessageBoxStyleType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxStyleType3 {
            get {
                return ResourceManager.GetString("MessageBoxStyleType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        public static string MessageBoxStyleType4 {
            get {
                return ResourceManager.GetString("MessageBoxStyleType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string SplitterDirection0 {
            get {
                return ResourceManager.GetString("SplitterDirection0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft.
        /// </summary>
        public static string SplitterDirection1 {
            get {
                return ResourceManager.GetString("SplitterDirection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SplitterPosition0 {
            get {
                return ResourceManager.GetString("SplitterPosition0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string SplitterPosition1 {
            get {
                return ResourceManager.GetString("SplitterPosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string SplitterPosition2 {
            get {
                return ResourceManager.GetString("SplitterPosition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string SplitterVisibility0 {
            get {
                return ResourceManager.GetString("SplitterVisibility0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string SplitterVisibility1 {
            get {
                return ResourceManager.GetString("SplitterVisibility1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string SplitterVisibility2 {
            get {
                return ResourceManager.GetString("SplitterVisibility2", resourceCulture);
            }
        }
    }
}
