//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TensorStack.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TensorStack.WPF.Resources.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Audio.
        /// </summary>
        public static string Tooltip_ClearAudio {
            get {
                return ResourceManager.GetString("Tooltip_ClearAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Mask.
        /// </summary>
        public static string Tooltip_ClearMask {
            get {
                return ResourceManager.GetString("Tooltip_ClearMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Video.
        /// </summary>
        public static string Tooltip_ClearVideo {
            get {
                return ResourceManager.GetString("Tooltip_ClearVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Auto-Play.
        /// </summary>
        public static string Tooltip_DisableAutoPlay {
            get {
                return ResourceManager.GetString("Tooltip_DisableAutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Auto-Replay.
        /// </summary>
        public static string Tooltip_DisableAutoReplay {
            get {
                return ResourceManager.GetString("Tooltip_DisableAutoReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to move.
        /// </summary>
        public static string Tooltip_DragToMove {
            get {
                return ResourceManager.GetString("Tooltip_DragToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Mode.
        /// </summary>
        public static string Tooltip_EditDrawMode {
            get {
                return ResourceManager.GetString("Tooltip_EditDrawMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Mode.
        /// </summary>
        public static string Tooltip_EditEraseMode {
            get {
                return ResourceManager.GetString("Tooltip_EditEraseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Mode.
        /// </summary>
        public static string Tooltip_EditMouseMode {
            get {
                return ResourceManager.GetString("Tooltip_EditMouseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move/Resize Mode.
        /// </summary>
        public static string Tooltip_EditResizeMode {
            get {
                return ResourceManager.GetString("Tooltip_EditResizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mode.
        /// </summary>
        public static string Tooltip_EditSelectMode {
            get {
                return ResourceManager.GetString("Tooltip_EditSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto-Play.
        /// </summary>
        public static string Tooltip_EnableAutoPlay {
            get {
                return ResourceManager.GetString("Tooltip_EnableAutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto-Replay.
        /// </summary>
        public static string Tooltip_EnableAutoReplay {
            get {
                return ResourceManager.GetString("Tooltip_EnableAutoReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        public static string Tooltip_LoadImage {
            get {
                return ResourceManager.GetString("Tooltip_LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image Mask.
        /// </summary>
        public static string Tooltip_LoadImageMask {
            get {
                return ResourceManager.GetString("Tooltip_LoadImageMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Mode - Discard Mask.
        /// </summary>
        public static string Tooltip_MaskModeDiscard {
            get {
                return ResourceManager.GetString("Tooltip_MaskModeDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Mode - Keep Mask.
        /// </summary>
        public static string Tooltip_MaskModeKeep {
            get {
                return ResourceManager.GetString("Tooltip_MaskModeKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse wheel to zoom.
        /// </summary>
        public static string Tooltip_MouseZoom {
            get {
                return ResourceManager.GetString("Tooltip_MouseZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Audio File.
        /// </summary>
        public static string Tooltip_OpenAudioFile {
            get {
                return ResourceManager.GetString("Tooltip_OpenAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Video File.
        /// </summary>
        public static string Tooltip_OpenVideo {
            get {
                return ResourceManager.GetString("Tooltip_OpenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Audio File.
        /// </summary>
        public static string Tooltip_SaveAudioFile {
            get {
                return ResourceManager.GetString("Tooltip_SaveAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Video File.
        /// </summary>
        public static string Tooltip_SaveVideo {
            get {
                return ResourceManager.GetString("Tooltip_SaveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Player.
        /// </summary>
        public static string Tooltip_VideoModeFrames {
            get {
                return ResourceManager.GetString("Tooltip_VideoModeFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Frame Viewer.
        /// </summary>
        public static string Tooltip_VideoModePlayer {
            get {
                return ResourceManager.GetString("Tooltip_VideoModePlayer", resourceCulture);
            }
        }
    }
}
