<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-windows10.0.17763.0;net10.0-windows10.0.17763.0</TargetFrameworks>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <!--Projects-->
  <ItemGroup Condition=" '$(Configuration)' == 'Debug'">
    <ProjectReference Include="..\TensorStack.Media\TensorStack.Media.csproj" />
  </ItemGroup>

  <!--Packages-->
  <ItemGroup Condition=" '$(Configuration)' == 'Release'">
    <PackageReference Include="TensorStack.Media" Version="$(Version)" />
  </ItemGroup>

  <!--Common Packages-->
  <ItemGroup>
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
  </ItemGroup>

  <!--Binaries-->
  <ItemGroup>
    <Content Include="ffmpeg.exe" Pack="true" PackagePath="contentFiles\any\any\" CopyToOutputDirectory="Always" PackageCopyToOutput="true" />
    <None Include="ffmpeg.exe" Pack="false" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ffprobe.exe" Pack="true" PackagePath="contentFiles\any\any\" CopyToOutputDirectory="Always" PackageCopyToOutput="true" />
    <None Include="ffprobe.exe" Pack="false" />
  </ItemGroup>

  <!--Nuget Settings-->
  <PropertyGroup>
    <Title>$(AssemblyName)</Title>
    <PackageId>$(AssemblyName)</PackageId>
    <Product>$(AssemblyName)</Product>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Windows audio processing with FFmpeg integration.</Description>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <None Remove="README.md" />
    <None Remove="Icon.png" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\Assets\Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="TensorStack.Media.Windows.targets" Pack="true" PackagePath="buildTransitive\" />
  </ItemGroup>

</Project>
