<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--DirectML.dll content warning-->
    <NoWarn>$(NoWarn);NU5100</NoWarn>
  </PropertyGroup>

  <!--Projects-->
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <ProjectReference Include="..\TensorStack.Common\TensorStack.Common.csproj" />
  </ItemGroup>

  <!--Packages-->
  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <PackageReference Include="TensorStack.Common" Version="$(Version)" />
  </ItemGroup>

  <!--Common Packages-->
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.29.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
  </ItemGroup>

  <!--Binaries-->
  <ItemGroup>
    <Content Include="DirectML.dll" Pack="true" PackagePath="contentFiles\any\any\" CopyToOutputDirectory="Always" PackageCopyToOutput="true" />
    <None Include="DirectML.dll" Pack="false" />
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <Microsoft_AI_DirectML_SkipLibraryCopy>True</Microsoft_AI_DirectML_SkipLibraryCopy>
    <Microsoft_AI_DirectML_SkipDebugLayerCopy>True</Microsoft_AI_DirectML_SkipDebugLayerCopy>
  </PropertyGroup>

  <!--Nuget Settings-->
  <PropertyGroup>
    <Title>$(AssemblyName)</Title>
    <PackageId>$(AssemblyName)</PackageId>
    <Product>$(AssemblyName)</Product>
    <Description></Description>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Core library for ONNX model/session management.</Description>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <None Remove="README.md" />
    <None Remove="Icon.png" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
    </None>
    <None Include="..\Assets\Icon.png">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
    </None>
  </ItemGroup>

</Project>