<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.0.1</Version>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>

  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.GC.Server" Value="true" />
    <RuntimeHostConfigurationOption Include="System.GC.Concurrent" Value="true" />
    <RuntimeHostConfigurationOption Include="System.GC.LatencyMode" Value="1" />
    <RuntimeHostConfigurationOption Include="System.GC.LargeObjectHeapCompactionMode" Value="2" />
  </ItemGroup>

  <!--Projects-->
  <ItemGroup>
    <ProjectReference Include="..\..\TensorStack.Common\TensorStack.Common.csproj" />
    <ProjectReference Include="..\..\TensorStack.Extractors\TensorStack.Extractors.csproj" />
    <ProjectReference Include="..\..\TensorStack.Upscaler\TensorStack.Upscaler.csproj" />
    <ProjectReference Include="..\..\TensorStack.Python\TensorStack.Python.csproj" />
    <ProjectReference Include="..\..\TensorStack.Media.SkiaSharp\TensorStack.Media.SkiaSharp.csproj" />
    <ProjectReference Include="..\..\TensorStack.OnnxRuntime.DML\TensorStack.OnnxRuntime.DML.csproj" />
  </ItemGroup>

  <!--Nuget Packages-->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>

  <!--Binaries-->
  <ItemGroup>
    <Reference Include="CSnakes.Runtime">
      <HintPath>CSnakes.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
